version: '3.8'

services:

  dbms:
    
    image: mariadb:latest

    container_name: mariadb 
    
    restart: 'always'

    ports:
      - "3306:3306"
    
    volumes:
      - "/var/lib/mysql/data:${MARIADB_DATA_DIR}"
      - "/var/lib/mysql/logs:${MARIADB_LOG_DIR}"
      - /var/docker/mariadb/conf:/etc/mysql
    
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"


  web:
  
    image: php:8.2-apache
    
    container_name: apache
    
    ports:
      - "8888:80"
    
    volumes:
      - /home/imdonkey/Projects/php:/var/www/html
    
    command: sh -c "docker-php-ext-install mysqli && apache2-foreground"
  
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data

    depends_on:
      - dbms


  web_gui:

    image: adminer:latest
    
    container_name: web_gui
    
    restart: 'always'

    ports:
      - 8080:8080

    depends_on:
      - dbms

